swagger: '2.0'
info:
  description: "イントワークスAPI的なもの"
  version: 1.0.0
  title: "アプリコンペ_teamC API"
host: localhost
basePath: /intworks/v1
tags:
  - name: "カスタマ情報"
    description: "カスタマ関連情報 ※カスタマ= 契約者"
  - name: "チェックグループ情報"
    description: "チェックグループの一覧取得、登録、更新、削除を行うAPI"
  - name: "チェックアイテム情報"
    description: "チェックアイテムの取得、登録、更新、削除を行うAPI"
  - name: "チェックグループの操作"
    description: "チェックアイテム一覧のチェック完了などを行うAPI"
schemes:
  - http
paths:
  /customers/{customer_id}/users/{user_id}:
    get:
      tags:
      - "カスタマ情報"
      summary: "確認者情報取得"
      description: "確認者情報取得するAPI"
      produces:
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "user_id"
          in: "path"
          description: "ユーザID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
          
  /customers/{customer_id}/check_groups:
    get:
      tags:
      - "チェックグループ情報"
      summary: "チェックグループ一覧取得"
      description: "チェックグループの一覧を取得するAPI。データは複数件取得する。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    put:
      tags:
      - "チェックグループ情報"
      summary: "チェックグループ登録"
      description: "チェックグループを登録するAPI。登録は１件のチェックグループを登録する。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
  /customers/{customer_id}/check_groups/{check_groups_id}:
    post:
      tags:
      - "チェックグループ情報"
      summary: "チェックグループの更新"
      description: "チェックグループを更新するAPI。更新は必ず１件のチェックグループを対象とする。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーグループID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    delete:
      tags:
      - "チェックグループ情報"
      summary: "チェックグループの更新"
      description: "チェックグループの一覧を取得するAPI"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
          
  /customers/{customer_id}/check_groups/{check_groups_id}/check_items:
    get:
      tags:
      - "チェックアイテム情報"
      summary: "チェックアイテム一覧の取得"
      description: "チェックグループに所属するチェックアイテム一覧を取得するAPI。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーグループID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    put:
      tags:
      - "チェックアイテム情報"
      summary: "チェックアイテム一覧の取得"
      description: "チェックグループに所属するチェックアイテムを取得するAPI。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
  /customers/{customer_id}/check_groups/{check_groups_id}/check_items/{check_item_id}:
    get:
      tags:
      - "チェックアイテム情報"
      summary: "チェックアイテム単体の取得"
      description: "チェックグループに所属するチェックアイテム単体を取得するAPI。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーグループID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_item_id"
          in: "path"
          description: "チェックアイテムID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    post:
      tags:
      - "チェックアイテム情報"
      summary: "チェックアイテムの更新"
      description: "チェックグループに所属するチェックアイテムを更新するAPI。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_item_id"
          in: "path"
          description: "チェックアイテムID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"          
    delete:
      tags:
      - "チェックアイテム情報"
      summary: "チェックアイテムの削除"
      description: "チェックグループに所属するチェックアイテムを削除するAPI。"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_item_id"
          in: "path"
          description: "チェックアイテムID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"   
          
  /customers/{customer_id}/check_groups/{check_groups_id}/result:
    put:
      tags:
      - "チェックグループの操作"
      summary: "チェックグループの確認完了を登録"
      description: "チェックグループの確認が完了したタイミングでログを記録するためのAPI
      。登録情報には各チェックアイテムのチェックされたものだけ記録され、それ以外はリクエストに含めない。また各チェックアイテムをチェックした時間も記録される"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "customer_id"
          in: "path"
          description: "カスタマーID"
          required: true
          type: "integer"
          format: "int64"
        - name: "check_groups_id"
          in: "path"
          description: "カスタマーグループID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/check_groups"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
definitions:
  check_groups:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      officeid:
        type: integer
        format: int64
      nfctagid:
        type: integer
        format: int64
      check:
        type: object
        properties:
          status:
            type: integer
          date:
            type: string
            format: date-time
      others:
        type: object
        properties:
          status:
            type: integer
          biko:
            type: string
    xml:
      name: checklist
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
